// Generated by dts-bundle-generator v8.0.1

import React from 'react';

export declare const ColorPicker: (props: ColorPickerProps) => React.JSX.Element;
export interface ColorPickerProps {
	title?: string;
}

export {};
